title: ビールは何にでもあう
description: >- # this means to ignore newlines until "baseurl:"
   Webサービス企業ではたらくOLが仕事とかプライベートのことなどを記録
domain: kashimg.github.io
url: https://kashimg.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Home
paginate: 10
paginate_path: "/pages/page:num/"