title: ビールは何にでもあう
description: >- # this means to ignore newlines until "baseurl:"
   Webサービス企業ではたらくOLが仕事とかプライベートのことなどを記録
domain: blog.kashimg.xyz
url: https://blog.kashimg.xyz

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag